---
- name: apachephp | Install Apache
  sudo: yes
  apt: pkg=apache2 state=latest

- name: apachephp | Install php5
  sudo: yes
  apt: pkg=php5 state=latest

- name: Apache Modules
  shell: a2enmod {{ item }}
  notify: restart apache
  with_items:
    - rewrite
    - vhost_alias
    - headers
    - expires
    - filter

- name: apachephp | Change default apache site
  sudo: yes
  template: src=apachephp/templates/vhost.conf.tpl dest=/etc/apache2/sites-available/default
  notify: restart apache