rabbitmqplugins:
  - rabbitmq_auth_backend_ldap
  - rabbitmq_auth_mechanism_ssl
  - rabbitmq_consistent_hash_exchange
  - rabbitmq_federation
  - rabbitmq_federation_management
  - rabbitmq_management
  - rabbitmq_management_agent
  - rabbitmq_mqtt
  - rabbitmq_shovel
  - rabbitmq_shovel_management
  - rabbitmq_stomp
  - rabbitmq_management_visualiser
  - rabbitmq_tracing
  - rabbitmq_web_stomp
  - rabbitmq_web_stomp_examples
  - rabbitmq_amqp1_0